name: DummyJSON Environment
variables:
  baseUrl:
    value: 'https://dummyjson.com'
    enabled: true
  loginUsername:
    value: emilys
    enabled: true
  loginPassword:
    value: emilyspass
    enabled: true
  authToken:
    value: ''
    enabled: true
  environmentName:
    value: dev
    enabled: true
  expectedResponseTime:
    value: '2000'
    enabled: true
